services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    networks:
      - catalog

networks:
  catalog: